### PR TITLE
inventory is added

### PR DESCRIPTION
**Pull request by asranjith**
Is this pom is required please review rockyasr

### CODE REVIEW

**Comment by asranjith** [comment]
yes asrranjith you have to create pom page in more option like tools, analytics, marketing, support, inventory, sales.

**Review by asranjith — COMMENTED** [review]
add the element present in inventory

**Comment by asranjith** [comment]
i added the element in inventory

**Review by asranjith — COMMENTED** [review]
Done

**Comment by rockyasr** [comment]
asrranjith your code is merged

**Pull request merged**
